TABLE_DOCS = [
    {"table": "hourly_crimes", "columns": "hour INT (0-23), crime_count",
     "description": "Total crimes for each hour of the day. Peak hours, night vs day. Example: What hour has the most crime?"},
    {"table": "time_period_crimes", "columns": "time_period, total_crimes",
     "description": "Total crimes by time period of day (e.g. morning, afternoon, evening, night). Example: Is crime higher at night or in the morning?"},
    {"table": "monthly_crimes", "columns": "month INT (1-12), total_crimes",
     "description": "Total crimes per calendar month. Seasonality by month. Example: Which month has the most crime?"},
    {"table": "season_crimes", "columns": "season, total_crimes",
     "description": "Total crimes per season (winter, spring, summer, fall). Example: Is crime higher in summer than winter?"},
    {"table": "yearly_crimes", "columns": "year, total_crimes",
     "description": "Total crimes per year. Long-term trends over time. Example: How has crime changed over the years?"},
    {"table": "great_recession_by_type", "columns": "primary_type, total",
     "description": "Crime counts by primary crime type during the Great Recession period. Example: What crimes were most common during the recession?"},
    {"table": "holidays", "columns": "holiday_date DATE, holiday_name",
     "description": "Lookup list of holiday dates and names. Not crime counts. Example: What holidays are tracked?"},
    {"table": "holiday_vs_nonholiday", "columns": "day_type, total_crimes",
     "description": "Total crimes on holidays versus non-holidays. Example: Is crime higher on holidays?"},
    {"table": "christmas_by_type", "columns": "primary_type, total",
     "description": "Crime counts by type on Christmas. Example: What crimes happen most on Christmas?"},
    {"table": "christmas_vs_nonchristmas_by_type", "columns": "day_type, primary_type, total",
     "description": "Crime counts by type comparing Christmas days to other days. Example: Does theft rise on Christmas?"},
    {"table": "halloween_by_type", "columns": "primary_type, total",
     "description": "Crime counts by type on Halloween. Example: What crimes happen most on Halloween?"},
    {"table": "halloween_vs_nonhalloween_by_type", "columns": "day_type, primary_type, total",
     "description": "Crime counts by type comparing Halloween to other days."},
    {"table": "thanksgiving_by_type", "columns": "primary_type, total",
     "description": "Crime counts by type on Thanksgiving."},
    {"table": "thanksgiving_vs_nonthanksgiving_by_type", "columns": "day_type, primary_type, total",
     "description": "Crime counts by type comparing Thanksgiving to other days."},
    {"table": "community_area_crimes", "columns": "community_area, total_crimes",
     "description": "Total crimes per Chicago community area (neighborhood). Example: Which neighborhoods have the most crime?"},
    {"table": "crimes_by_location", "columns": "location_category, total_crimes",
     "description": "Total crimes per location category (street, residence, store, etc.). Example: Where do most crimes occur?"},
    {"table": "crimes_by_location_and_type", "columns": "location_category, primary_type, total, location_total",
     "description": "Crime counts by location category and crime type. Example: What is the most common crime at residences?"},
    {"table": "theft_by_location", "columns": "location_description, total_thefts, total_crimes",
     "description": "Thefts versus total crimes for each location description. Example: Where does theft happen most?"},
    {"table": "airport_theft_count_comparison", "columns": "location_type, theft_count, total_crimes, theft_rate",
     "description": "Theft counts and theft rate at airport locations compared with other locations."},
    {"table": "downtown_vs_residential_theft_robbery", "columns": "area_type, tr_crimes, total_crimes, rate",
     "description": "Theft and robbery counts and rate in downtown versus residential areas."},
    {"table": "transit_vs_commercial_robbery_count", "columns": "location_type, robbery_count, total_crimes, robbery_rate",
     "description": "Robbery counts and rate at transit locations versus commercial locations."},
    {"table": "sport_location_crimes", "columns": "crime_category, total_crimes",
     "description": "Crimes near sports venues by crime category."},
    {"table": "sport_location_crimes_by_type", "columns": "location_description, primary_type, total_crimes",
     "description": "Crimes at sports venues by venue and crime type. Example: Which crime is most common at stadiums?"},
]
